version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./azdevops-service
    env_file:
      - ${ENV_FILE}
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    ports:
      - 3001:3001
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./azdevops-ui
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always

volumes:
  redis_data: